export const GET_CURRENT_LOCATION_SUCCESS = 'GET_CURRENT_LOCATION_SUCCESS';
export const GET_CURRENT_LOCATION_REQUEST = 'GET_CURRENT_LOCATION_REQUEST';

export const GET_ADDRESS_INPUT = 'GET_ADDRESS_INPUT';
export const TOGGLE_SEARCH_RESULT = 'TOGGLE_SEARCH_RESULT';
export const SET_PICKUP_AND_DROPOFF_TO_FALSE = 'SET_PICKUP_AND_DROPOFF_TO_FALSE'

export const GET_ADDRESS_PREDICTIONS = 'GET_ADDRESS_PREDICTIONS';
export const GET_SELECTED_ADDRESS = 'GET_SELECTED_ADDRESS';
export const GET_DISTANCE_MATRIX = 'GET_DISTANCE_MATRIX';